export type BasicShapeType =
	| "Rectangle"
	| "Triangle"
	| "ReversedTriangle"
	| "Circle"
	| "ArrowLeft"
	| "ArrowLeftRight"
	| "ArrowRight"
	| "ArrowBlockLeft"
	| "ArrowBlockRight"
	| "BracesLeft"
	| "BracesRight"
	| "Cloud"
	| "Cross"
	| "Cylinder"
	| "Hexagon"
	| "IRCloud"
	| "Octagon"
	| "Parallelogram"
	| "ReversedParallelogram"
	| "Pentagon"
	| "PredefinedProcess"
	| "Rhombus"
	| "RoundedRectangle"
	| "SpeachBubble"
	| "Star"
	| "Trapezoid";

export type BPMN_ShapeType =
	| "BPMN_Gateway"
	| "BPMN_DataStore"
	| "BPMN_GatewayParallel"
	| "BPMN_GatewayXOR"
	| "BPMN_EndEvent"
	| "BPMN_StartEvent"
	| "BPMN_StartEventNoneInterrupting"
	| "BPMN_IntermediateEvent"
	| "BPMN_IntermediateEventNoneInterrupting"
	| "BPMN_Group"
	| "BPMN_Participant"
	| "BPMN_Task"
	| "BPMN_Transaction"
	| "BPMN_EventSubprocess"
	| "BPMN_Annotation"
	| "BPMN_DataObject";

export type ShapeType = BasicShapeType | BPMN_ShapeType;
