export const defaultCursors = [
	'default',
	'auto',
	'text',
	'crosshair',
	'move',
	'all-scroll',
	'wait',
	'not-allowed',
	'pointer',
	'grab',
	'grabbing',
	'webkit-grab',
	'webkit-grabbing',
	'zoom-in',
	'zoom-out',
	'col-resize',
	'e-resize',
	'ew-resize',
	'n-resize',
	'ne-resize',
	'nesw-resize',
	'ns-resize',
	'nw-resize',
	'nwse-resize',
	'row-resize',
	's-resize',
	'se-resize',
	'sw-resize',
	'w-resize',
	'alias',
	'cell',
	'context-menu',
	'copy',
	'help',
	'no-drop',
	'none',
	'progress',
	'sticker-purple',
	'sticker-pink',
	'sticker-sky-blue',
	'sticker-blue',
	'sticker-green',
	'sticker-light-green',
	'sticker-orange',
	'sticker-yellow',
	'sticker-light-gray',
	'sticker-gray',
] as const;

export const customCursors = ['pen', 'eraser', 'comment'] as const;

export type Cursor = (typeof defaultCursors)[number] | string;
export type CursorName = (typeof defaultCursors)[number] | (typeof customCursors)[number];
export type CursorsMap = Partial<Record<CursorName, Cursor>>;
